### ISSUE TITLE
TakeOptions should support hide_selectors customization

### ISSUE THREAD

**Issue by kjohnson** [screenshotone/phpsdk#1]
The documentation mentions a [hide_selectors](https://screenshotone.com/docs/options/#hide_selectors) customization option, but this is not supported by the PHP SDK.

> ## Customization
> ### [hide_selectors](https://screenshotone.com/docs/options/#hide_selectors)
>
> The hide_selectors option allows hiding elements before taking a screenshot. You can specify as many selectors as you wish. All elements that match each selector will be hidden by setting the display style property to none !important.
>
> An example of the request URL with hide_selectors=.a&hide_selectors=.b:

**Comment by krasun** [comment]
Hi, thanks for the pull request. I merged it and updated the SDK to version `v1.0.2`. 

I am sorry for that. In the past months, I added many new features but haven't added them to the SDKs. I will take time and update them all.
