### ISSUE TITLE
Missing support for the "ignore_host_errors" option

### ISSUE THREAD

**Issue by schams-net** [screenshotone/phpsdk#3]
If the remote site responds with an error, for example HTTP status code 404 ("File not found"), creating a screenshot fails. To ignore errors returned by the site and render the error page, the `ignore_host_errors` option can be set to `true`. This option is currently missing in the PHP SDK.

**Comment by krasun** [comment]
Thanks a lot for reporting! Sorry for the huge delay in response, I somehow missed the message. 

I deployed the change as 1.0.3 at https://packagist.org/packages/screenshotone/sdk.
